# github_connector_config.yml
github:
  enabled: true
  config:
    # Authentication and API endpoint settings.
    github_token: "your_github_personal_access_token_here"
    organization: "your_organization_name_here"
    api_endpoint: "https://api.github.com/"
    
    # Concurrency settings.
    max_workers: 10
    api_timeout: 10  # Timeout in seconds for API requests.
    
    # Rate limit retry policy.
    rate_limit_retry:
      max_attempts: 5
      base_delay: 1.0  # Base delay in seconds for exponential backoff.
    
    # Kafka topic settings for GitHub discovery.
    # Since resource and access log discovery are handled separately,
    # only identity and privilege topics are configured here.
    kafka_topics:
      identity: "github-identity"
      privilege: "github-privilege"

